<?
$PERM["izbrannoe"]["2"]="D";
$PERM["izbrannoe"]["3"]="D";
$PERM["izbrannoe"]["4"]="D";
$PERM["izbrannoe"]["8"]="W";
$PERM["izbrannoe"]["6"]="R";
$PERM["izbrannoe"]["7"]="D";
$PERM["izbrannoe"]["5"]="D";
$PERM["izbrannoe"]["*"]="D";
?>